### ISSUE TITLE
Add MusicWall.app

### ISSUE THREAD

**Issue by carlosdetorres** [ad-si/awesome-music-production#161]
Hi!

I wanted to make a PR to add [MusicWall](https://musicwall.app) but I'm not sure in which group could fit better, because is not Music Distribution but is more like "Social Distribution"

```
- [MusicWall] - Free music landings for producers / engineers with Spotify credits

[MusicWall]: https://musicwall.app
```

I made MusicWall as a Software Engineer and Music Producer to help producers and studios to showcase their career and create a profile to share their portfolios to future clients. 

I have new clients everyday and seems like a nice solution for producers to show their portfolios.

Which group would be better for it? Webapp? 

Thanks in advance!

**Comment by ad-si** [comment]
Hi, thanks for the submission!

I added a new section "Music Promotion" in 44a08430c14614dd09a8afe4e26765ff87eb67ef
