### ISSUE TITLE
Suggested Software, Apps, Links etc.

### ISSUE THREAD

**Issue by PGordonLegiten** [ad-si/awesome-music-production#171]
**Software**

- Tracktion Waveform: [https://www.tracktion.com/products/waveform-free](https://www.tracktion.com/products/waveform-free) Full Feature DAW

- Acid Pro 11: [magix.com/us/music-editing/acid/](https://www.magix.com/us/music-editing/acid/) Classic Acid Sampler

- FLstudio: [flstudio.com.au](https://www.flstudio.com.au/) Ultimate Beatmapper for Everything Hiphop. Fruity Loops

**App**

- Remix Live: [mixvibes.com/remixlive](https://www.mixvibes.com/remixlive) _An Amazing Sampler, Live DJ Performer Pads, Edit Samples and Record or Export production. Mix and match samples. Onscreen Keyboard with Scale lock, Drumpad, Sequencer All in One!_
[Android](http://bit.ly/remixlive-android%E2%80%8B) , [iOS](http://bit.ly/remixlive-ios%E2%80%8B), [Amazon](https://www.amazon.com/Mixvibes-Remixlive-Make-Music-Beats/dp/B09TW9QCGV/ref=sr_1_6?crid=QQ67HFQ25S3D&keywords=remixlive&qid=1668526572&sprefix=remixlive%2Caps%2C139&sr=8-6)

- FLstudio Mobile : _Ultimate hiphop sampler beatmapper in your pocket._ 
 [Android](https://play.google.com/store/apps/details?id=com.imageline.FLM&hl=en_US&gl=US) 

- 432 Player: [432player.com](https://www.432player.com) Music player that will retune local files to A-432hz or C-528hz . Pro includes 432 Radio.  [Android](https://play.google.com/store/apps/details?id=com.appums.music_pitcher) , [iOS](https://itunes.apple.com/us/app/432-player/id633600716?ls=1&mt=8) , [PC/Mac](https://432hz.live/)

**Comment by ad-si** [comment]
Thanks!

Added in c2de5cd, 8635f57, b9d656d, and 8c8e276.
