### ISSUE TITLE
Audio libs

### ISSUE THREAD

**Issue by adius** [ad-si/awesome-music-production#4]
- https://github.com/kinetiknz/cubeb 
- https://github.com/klingtnet/rsoundio
- https://github.com/ul/soundio
- https://github.com/pocket7878/cl-libsoundio
- https://github.com/luapower/libsoundio
- https://github.com/raph-amiard/ada-soundio

**Comment by ad-si** [comment]
Added in f2025f6180b0242729e98897e5929b3ba19f490d
