### ISSUE TITLE
supercollider

### ISSUE THREAD

**Issue by adius** [ad-si/awesome-music-production#43]
https://github.com/supercollider/supercollider

**Comment by ad-si** [comment]
Added in 766b101a18985b9a118d2203f6b13329d698e45b

**Comment by cicerojones** [comment]
It's great that Supercollider is on here, but "Webapp" doesn't seem the best category for something that bills itself as "An audio server, programming language, and IDE." AFAIK there is no common way to use Supercollider from a web browser.

Perhaps "Library" is the best approximation on this list, but I think something more like "Programming Environment" might be worth introducing, in which case Pure Data and Max/MSP (among others) could be added. Worth considering!
