### ISSUE TITLE
surge-synthesizer

### ISSUE THREAD

**Issue by ad-si** [ad-si/awesome-music-production#61]
https://github.com/surge-synthesizer/surge

**Comment by eoj31** [comment]
hey there im having an issue with automation with surge on LogiX. whenever i move anything while on touch mode for example when i move the pitch and i want to automate it by touch automation is is not working its is not sending the signal. ive been using surge for years and never went through this problem with the older versions. please help thank you

**Comment by ad-si** [comment]
You're in the wrong repository!
You probaly want to post your question here: https://github.com/surge-synthesizer/surge/issues
Good luck! 😉

**Comment by eoj31** [comment]
> You're in the wrong repository!
> You probaly want to post your question here: https://github.com/surge-synthesizer/surge/issues
> Good luck! 😉

thank you, i thought so :)

**Comment by ad-si** [comment]
Added in 61639e2
